### ISSUE TITLE
Should the pdf export really plot **all** systems?

### ISSUE THREAD

**Issue by Julianfritzsche2** [santiago-sanitation-systems/Santiago.jl#31]
The Best Practice Runfile now plots all systems as pdf, not only selectedSys. Would users want to plot all possible systems? This might still need another thought, also about the creation of a single pdf with all systems and for what it will be used.

**Comment by scheidan** [comment]
Probably not in most cases. Creating (especially the merging) fo 100k+ pdf's is tricky and we did not yet find a robust solution. Maybe we can simply collect some tricks and tools that one could try.

(PS: It would be better to use the issue tracker here only for `Santiago.jl` related things, like bugs or missing functions. Topics regarding the wiki should we collect somewhere else, because they mess up the automatic release notes)

**Comment by Julianfritzsche2** [comment]
Okay, thanks and sorry!

**Comment by scheidan** [comment]
No problem :)
