### ISSUE TITLE
Perhaps change "range" to "uniform" in Santiago.jl/src/performanceFunctions.jl

### ISSUE THREAD

**Issue by Julianfritzsche2** [santiago-sanitation-systems/Santiago.jl#34]
If we want to use "uniform" instead of "range" we need to update the source code accordingly. However, Dorothee was not fully satisfied with the name "uniform" and we might have to discuss this with her. But the calculation seems to work if the source code _performanceFunctions.jl_ is modified.

**Comment by scheidan** [comment]
I'm not sure if `uniform` is a much better name than `range`. Because if it is used as Performance function it is anyway not a uniform _distribution_. That said, it would be easy to change the code, but it would break **all** existing input files.

I close this, but if Dorothee really want that, just open it again.
