### ISSUE TITLE
enable plotting for all systems if possible (merge or not)

### ISSUE THREAD

**Issue by spuhlerd** [santiago-sanitation-systems/Santiago.jl#43]
If too much effort, stay with all plots but unmerged files

**Comment by scheidan** [comment]
We have the function `dot_file` in Santiago. With this, you can easily make the pdf's as described in the wiki:
```Julia
for (i, sys) in enumerate(allSys) 
    
    # First write a dot file
    dot_file(sys, "$outputFolder/plots/temp.dot")
    
    # Then, convert it to pdf (The program `graphviz` must be installed on the system)
    run(`dot -Tpdf $outputFolder/plots/temp.dot -o $outputFolder/plots/systems_$i.pdf`)

end
```

We cannot add a complete `plot_system` function to Santiago, because we need to install the  `graphviz` program manually. I haven't found a way to do this automatically that works on all systems.
