### ISSUE TITLE
add new target to select_systems()

### ISSUE THREAD

**Issue by spuhlerd** [santiago-sanitation-systems/Santiago.jl#77]
add "product" "total" for focus "recovery_ratio"

**Comment by spuhlerd** [comment]
total is the sum of the recovery_ratio of each of the four products

**Comment by spuhlerd** [comment]
call "all" to avoid confusion with totalsolids

**Comment by scheidan** [comment]
Relevant Santiago.jl issue: santiago-sanitation-systems/Santiago.jl#77

**Comment by scheidan** [comment]
I have an implementation for this ready. It can be uses like this:
```Julia
select_systems(allSys, 7, target="all" => "recovery_ratio")
select_systems(allSys, 7, target="all" => "lost", maximize=false)
```
and it computes the sum of the targets over all products.

@spuhlerd Should we document this functionality? I tend to treat it as an internal special functionality, because we may sum over very different units which most likely does not have a useful interpretation. Or at least we should put a warning in the doc string.

**Comment by scheidan** [comment]
done
