### ISSUE TITLE
change simplifty_technames to keep transport information

### ISSUE THREAD

**Issue by spuhlerd** [santiago-sanitation-systems/Santiago.jl#84]
it makes sense to differentiate the techs and the techs_trans for templates as "transported" is among the criteria that characterise templates. this is urgently needed by the frontend why I have mareked this issue as priority.
To be implemented:
- currently techspertemplate() returns a list of all templates and the technology names as they have been imported. 
- when retrieving all tech names from the systems within a template check whether technologies do occur in their form without trans, with trans, or both
- if without trans, then the return is the techname
- if with trans, then the return is techname_trans
- if both, then two names are returned: techname and techname_trans

**Comment by SantiagoStudent** [comment]
This could be implemented in "symplify techs" within the techspertemplate functions.
E.g
Now from a set of techs {tech1_1, tech1_2_trans, tech2_1, tech2_2_trans, tech3_1} it returns now
{tech1, tech2, tech3}
in future it should return
{tech1, tech1_trans, tech2, tech2_trans, tech3}

**Comment by SantiagoStudent** [comment]
Techs with "_trans" could be named as "_centralised"

**Comment by scheidan** [comment]
I have an implementation ready for of that. However, this will break a lot of things in the frontend!

The new behavior is:
- the json system export distinguishes between techs `"mytech"` and `"mytech_trans"`
- dot file export distinguisheds between techs `"mytech"` and `"mytech_trans"`

but this leads to complications:
-  `appropriateness` (and `update_appropriateness!`) is computed only for `"mytech"` (as at this point `"mytech_trans"` do not yet exist)
- the arguments `techs_include` and `techs_exclude` of `select_systems()` distinguishes between  `"mytech"` and `"mytech_trans"`

That would mean that the fronted needs to take care that sometimes the same tech has different names... Do we really want that? Moreover because the distinguishes `"mytech"` / `"mytech_trans"` is an internal implementation detail, we never make a difference otherwise (e.g. tas or massflow calculations).

**Comment by scheidan** [comment]
The new plan:

1. add argument to `techs_per_template(systems::Array{System}; keep_trans=true)` so that the "mytech" are distiguished "mytech_trans" in the output

Or:

2. introduce this separate  `techs_per_template-web(systems::Array{System}`
3. modify back end accordingly

everything else we keep as it is

**Comment by scheidan** [comment]
Added `techs_per_template-web(systems::Array{System}`

**Comment by spuhlerd** [comment]
To test this, a new release is required. 
Should testing also directly be done for the webservice?

**Comment by spuhlerd** [comment]
@scheidan sanichoice front end is ready to work with the updated techs_per_template-web(systems::Array{System}) function.
