### ISSUE TITLE
select_systems considers only first number of name

### ISSUE THREAD

**Issue by spuhlerd** [santiago-sanitation-systems/Santiago.jl#85]
@scheidan 
For allSys with following templates:
 "ST.35 Urinal"
 "ST.33 Hybrid blackwater system with urine diversion"
 "ST.16 Centralized blackwater system with sludge"
 "ST.16 Centralized blackwater system with sludge"
 "ST.27 Onsite dry system with urine diversion without effluent transport"
 "ST.36 Controlled open defecation in humanitarian context"
'selectedSys2 = select_systems(allSys, 8,  templates_include=["ST.27"],templates_exclude=["ST.2"])'
returns 'Systems[]'

Is it possible, that with excluding "ST.2" also "ST.27" gets excluded?
Same happens online for the webservice:
If "ST.1" is included, he will also include ST.11, ST12,  etc...

Can you fix this? Afterwards probably Antti needs to relaunch Santiago once again...
Dorothee

**Comment by scheidan** [comment]
Yes, the current behavior is that "for the templates only the first few characters must be provided." Without this working interactively with the templates names would be very inconvinient. I see the following solutions:

1.Always use the complete template names when querying the webservice, i.e. `
"ST.27 Onsite dry system with urine diversion without effluent transport"` instead of `
"ST.27"`.
2. Make sure to uses strings that are long enough to be unique,  i.e.  `"ST.2 "` and  `"ST.27 "`, instead of `"ST.2"` and  `"ST.27"` 
3. Disable the automatic guessing of Santiago.jl
4. Add a check so that Santiago.jl will error if the abbreviated name is unique.

 The first two approacheds would not need a updated of the webservice. @spuhlerd What do you prefere?

**Comment by scheidan** [comment]
We decided for the following:
- The backend implements 2), i.e. adding a space after each number. This works with the current Santiago version.
- We implement 4) in Santiago, to avoid such confusion in the future.

**Comment by scheidan** [comment]
d31800d adds a more detailed explanation of the current behavior and a warning of potentially resulting confusion. Checking automatically for non-unique abbreviation would be a rather expensive operation and probably not good choice for the webservice.

It is still a bit risky because the current implementation cannot distiguisg between `"T easy template"` and `"T easy template with UDDT"`

So maybe we want to disable the automatic guessing by default and add an extra option to `select_system` to enable it? This would break a lot of scripts though.

**Comment by spuhlerd** [comment]
Currently template names are defined by T1. or T11. So if the "." is considered when calling the webservice, the problem should not occur anymore
